### ISSUE TITLE
Status not rendered on OCP 4.3

### ISSUE THREAD

**Issue by cvignola** [kappnav/issues#115]
There is a breaking API change in Kubernetes 1.16 ...

**Comment by paulben** [comment]
The change for OCP 4.3 / Kube 1.16 is that the group `apiextensions.k8s.io` has a new default version `v1` whereas before the default version was `v1beta1`. This is due to custom resource definitions going from beta to GA. App navigator currently only watches default resource versions. This fix changes App navigator to watch all versions of `apiextensions.k8s.io` so existing CustomResourceDefinitions with version `v1beta1` will be processed.

**Comment by juniartisu** [comment]
Open issue https://github.com/kappnav/issues/issues/117 to undo once this issue completed.
https://github.com/kappnav/controller/pull/31
https://github.com/kappnav/apis/pull/55
