### ISSUE TITLE
kAppNav installed with kabanero shows "unknown" status for application

### ISSUE THREAD

**Issue by gecock** [kappnav/issues#51]
kAppNav dashboard shows application status as `unknown`

- Installed kAppNav using kabanero install.
- Configured Tekton webhook to deploy Java MicroProfile application. 
- Application running fine and application pod is running fine.

![image](https://media.github.ibm.com/user/8554/files/081ce480-ee01-11e9-947d-73fd7e4890c9)

**Comment by marikaj123** [comment]
@gecock - According to @cvignola the issue can be document it as it's quite a limiting problem.  A quick fix can be provided as simply as respinning one of the docker images without impacting other parts of Kabanero.

**Comment by paulben** [comment]
Update: Found the problem, working with @cvignola  and @mchenggit on fix design. Debug images yielded necessary trace.

Problem is that knative has implemented their own Service kind (below) which causes kappnav to monitor that Service instead of the core Kubernetes Service.

`I1017 11:59:34.635917 1 controller.go:674] new startWatch kind: Service GVR: serving.knative.dev/v1alpha1, Resource=services`

**Comment by DoloresLopez** [comment]
@paulben can this be closed?

**Comment by marikaj123** [comment]
@gecock - Can you please verify and close the issue, the work is done.

**Comment by gecock** [comment]
We will verify using ICPA this week and reverify on Kab 0.3.0 in two weeks.

**Comment by bconey** [comment]
This has been verified as fixed.  The issue can be closed.
